swagger: '2.0'
info:
  description: Support Categories API
  version: 1.0.0
  title: Sony Support API
  contact:
    email: thibaut.bodart@sony.com

paths:
  /api/content/support/search:
    get:
      tags:
      - Search
      summary: search
      operationId: Search
      description: Organic search API for all content types
      produces:
      - application/json
      parameters:
      - in: query
        name: query
        description: Search term. Can be composed of multiple words. 
        required: true
        type: string
      - in: query
        name: locale
        required: true
        enum: ['en_GB', 'fr_FR', 'de_DE', 'fr_BE', 'nl_BE', 'en_SG', 'en_AP']
        type: string
      - in: query
        name: num
        description: Number of results to be returned by the API. 
        required: false
        default: 5
        type: integer
      - in: query
        name: type
        description: Type of the results to be returned by the API. 
        required: false
        type: string
        enum: ['faq', 'document', 'download', 'model', 'tutorial']
      - in: query
        name: start
        description: Index of the first result to return. This parameter is useful to build paging. 
        required: false
        default: 1
        type: integer
      - in: query
        name: searchInSubDocuments
        description: If set to 'true', the Search API will also look for matches in the subdocuments. E.g. The pages of the help-guides are considered as subdocuments.  Those matches are returned as sub-results of a specific result. 
        required: false
        default: false 
        type: boolean
      - in: query
        name: infer-context
        description: Defines whether the Search API will try to infer the context from the search term. For example, a search for 'ILCE-6000' will understand that the context is this specific model and will return a best match section in the response. In case of best match, the results are retrieved based on the context that has been infered from the query term. (We are planning to rename this parameter to inferContext for consistency reasons)
        required: false
        default: true
        type: boolean
      - in: query
        name: accessLevel
        description: If the value is 'cc-agent', the API will return internal FAQs that should not be visible on the web site for regular customers. Please note that if this parameter is defined, the API will validate the IP of the caller to make sure that the request is coming from one of the authorized CRM platforms. 
        required: false
        type: string
        enum: ['cc-agent']
      responses:
        200:
          description: Search Response
          schema:
            $ref: '#/definitions/SearchResponse'
        400:
          description: no content returned in case the locale provided is not known
  /api/content/support/{locale}/categories:
    get:
      tags:
      - Categories
      summary: top level categories
      operationId: Top Categories
      description: |
        Returns all the top level categories of the support catalogue. 
      produces:
      - application/json
      parameters:
      - in: path
        name: locale
        description: Locale of the web site 
        required: true
        enum: ['en_GB', 'fr_FR', 'en_SG']
        type: string
      responses:
        200:
          description: list of all the top level categories
          schema:
            $ref: '#/definitions/CategoryList'
        400:
          description: no content returned in case the locale provided is not known
  /api/content/support/{locale}/categories/{category}:
    get:
      tags:
      - Categories
      summary: sub categories
      operationId: Sub Categories
      description: |
        Returns all the top level categories of the support catalogue. 
      produces:
      - application/json
      parameters:
      - in: path
        name: locale
        description: Locale of the web site 
        required: true
        enum: ['en_GB', 'fr_FR', 'en_SG']
        type: string
      - in: path
        name: category
        description: Category of the support catalogue
        required: true
        type: string
      responses:
        200:
          description: list of all the sub categories
          schema:
            $ref: '#/definitions/CategoryList'
        400:
          description: no content returned in case the locale provided is not known
  /api/content/support/{locale}/suggest:
    get:
      tags:
      - Suggest
      summary: model suggestions
      operationId: Model Suggestions
      description: |
        Returns suggested models matching the query parameter. 
      produces:
      - application/json
      parameters:
      - in: query
        name: query
        description: Model prefix
        required: true
        type: string
      - in: path
        name: locale
        description: Locale of the web site 
        required: true
        enum: ['en_GB', 'fr_FR', 'en_SG']
        type: string
      responses:
        200:
          description: list of the top 5 suggestions matching the query
          schema:
            $ref: '#/definitions/Suggestions'
        400:
          description: no content returned in case the locale provided is not correct
    
definitions:
  SearchResponse:
     type: object
     required:
     - searchResponse
     properties:
      searchResponse:
         $ref: '#/definitions/SearchResponseDetails'
  SearchResponseDetails:
     type: object
     required:
     - count
     - start
     - end
     - results
     properties:
        count:
          type: integer
          description: Number of results available for the given search term and parameters. This attribute can be used to understand if more results are available and if it is therefore useful to execute another query to get additional results. 
          example: 3456 
        start:
          type: integer
          description: Indicates  the index of the first result included in the search response. 
          example: 5
        end: 
          type: integer
          description: Indicates the index of the last result included in the search response. Useful for retrieving the next page of results. 
          example: 10
        results: 
          $ref: '#/definitions/SearchResults'
  SearchResults:
      type: object
      required:
      - type
      - title
      - url
      properties:
        type:
           type: string
           enum: ['faq','document', 'model', 'tutorial', 'download']
           example: faq
        title:
          type: string
          example: Title of the search result
        description:
          type: string
          example: This description can be used as snippet for this result. 
          description: Snippet that can be used below the search result. Contains either the first words of the target URL or an excerpt of the content with highlights. Highlighted words will be surrounded by <em> HTML tags. 
        url:
          type: string
          example: http://sony-eur-eu-en-web--eur.custhelp.com/app/answers/detail/a_id/100281
          format: url
          description: URL of the search result
  Suggestions:
     type: object
     required:
     - suggestions
     properties:
       suggestions:
         type: array
         items: 
          $ref: '#/definitions/Suggestion'
  Suggestion:
      type: object
      required:
      - name
      - url
      properties:
        name:
          type: string
          example: DSC-HX350
        url:
          type: string
          description: Partial URL of the product page for this model (No host name). 
          example: /electronics/support/compact-cameras-dschx-series/dsc-hx350
  CategoryList:
    type: object
    required:
    - categories
    properties:
      categories: 
        type: array
        items: 
          $ref: '#/definitions/Category'
  Category:
    required:
      - name
      - displayName
    properties:
      name:
        type: string
        example: televisions-projectors
      displayName:
        type: string
        example:  Televisions and Projectors
      teaserImage:
        $ref: '#/definitions/ImageFamily'
  ImageFamily: 
    required: 
      - desktop
    properties:
      desktop:
        $ref: '#/definitions/Image'
  Image:
    required:
        - externalUrl
    properties:
        externalUrl:
          type: string
          format: url
          example: "//sonyglobal.scene7.com/is/image/gwtprod/aa67d598b260ba824817f9f8aa761c0e?fmt=png-alpha"
     
host: www.sony.co.uk